### PR TITLE
Fix #59 and #28.

### LINKED ISSUE #28: Crashes if fed nonexistent header
At least with the prebuilt dstep 0.1.0-2 on Arch, it crashes and spits out a backtrace if I feed it a non-existent C header, such as if I add a typo in the header's path.  It'd be nice if it issued an error instead, so the user knows what he did wrong.

### LINKED ISSUE #59: Shouldn't dstep exit with status code when there is some kind of error?
Currently `dstep` always returns `0` exit code, even on the failure (wrong input file/wrong command arguments). I believe it would be better, if it returns something other (e.g. 1) when there is an error. I would make `dstep` easier to integrate with some command line tools (and make testing easier).

### PR DESCRIPTION
**Pull request by ciechowoj**
Fix #59: Shouldn't dstep exit with status code when there is some kind of error?
Fix #28: Crashes if fed nonexistent header.

### CODE REVIEW

File: dstep/driver/Application.d [hunk 1]
```diff
@@ -76,13 +86,35 @@ class Application
...
+
+    static void enforceInputFilesExist(const Configuration config)
+    {
+        import std.exception : enforce;
+
+        foreach (inputFile; config.inputFiles)
+        {
+            enforce!DStepException(
+                exists(inputFile),
+                "dstep: error: file '" ~ inputFile ~ "' doesn't exist\n");
```
Comment (jacob-carlborg) [inline dstep/driver/Application.d]: Perhaps using `format` is cleaner.

File: unit_tests/IntegrationTests.d [hunk 2]
```diff
@@ -43,3 +46,30 @@ unittest
...
+}
+
+// DStep should exit with non-zero status when there is a syntax error in the input file.
+unittest
+{
+    auto result = executeShell("dstep test_files/syntax_error.h");
+
+    assert(result.status != 0);
+    assert(result.output.find("syntax_error.h"));
+}
```
Comment (jacob-carlborg) [inline unit_tests/IntegrationTests.d]: Is there a unit test to verify that it exits with status code 0 when it completes successfully?

File: dstep/driver/Application.d [hunk 3]
```diff
@@ -76,13 +86,35 @@ class Application
...
+                config,
+                fileName,
+                outputFilename);
 
-            conversionTask.executeInNewThread();
+            conversionTasks[index].executeInNewThread();
+        }
+
+        foreach (conversionTask; conversionTasks)
+            conversionTask.yieldForce();
```
Comment (jacob-carlborg) [inline dstep/driver/Application.d]: Is this used to force a task to complete?

**Comment by jacob-carlborg** [comment]
Please add an entry to the changelog as well.

File: dstep/driver/Application.d (hunk 3 above)
Comment (ciechowoj) [inline dstep/driver/Application.d]: It is used to rethrow the exceptions originated in the thread of that task.

File: unit_tests/IntegrationTests.d (hunk 2 above)
Comment (ciechowoj) [inline unit_tests/IntegrationTests.d]: Now, there is.

**Comment by ciechowoj** [comment]
> Please add an entry to the changelog as well.

Done.

**Comment by ciechowoj** [comment]
Is there anything more I can do here?

**Comment by jacob-carlborg** [comment]
👌

**Comment by ciechowoj** [comment]
Thanks.
