### PR TITLE
Fix #38: Spurious generation of variadic args.

### LINKED ISSUE #38: spurious generation of variadic args rather than implicit void ie () argument list
converting the mathgl headers

I got:
double mgl_rnd_ (...);

but it should just be:
double mgl_rnd();

hope this is not something simple I am doing wrong.  sorry, but I have not time right now to find the original header and try to replicate it.

### PR DESCRIPTION
**Pull request by ciechowoj**
Fixes issue #38. Makes dstep to translate function with empty parameter list as functions with empty parameter list. Adds a CLI switch to re-enable old behavior. 

Related info:
https://forum.dlang.org/thread/kywnjtmeifsetjchtrwu@forum.dlang.org
http://stackoverflow.com/a/13950800

### CODE REVIEW

File: unit_tests/issues/Issue38.d [hunk 1]
```diff
@@ -0,0 +1,43 @@
...
+C",
+q"D
+extern (C):
+
+void foo (...);
+void bar (const(char)* fmt, ...);
+void baz ();
+D", options);
+
+}
```
Comment (jacob-carlborg) [inline unit_tests/issues/Issue38.d]: Please add a reduced unit test as well in addition to this test specific to the issue.

**Comment by jacob-carlborg** [comment]
Please add an entry to the changelog.

File: unit_tests/issues/Issue38.d (hunk 1 above)
Comment (ciechowoj) [inline unit_tests/issues/Issue38.d]: Done.

**Comment by ciechowoj** [comment]
> Please add an entry to the changelog.

Done.

**Comment by jacob-carlborg** [comment]
Looking good, please rebase.

**Comment by ciechowoj** [comment]
Done.

**Comment by jacob-carlborg** [comment]
👌
